---
##########################
## Hadolint config file ##
##########################
ignored:
  - DL3006
  # DL3006: Always tag the version of an image explicitly
  # Ignored because we are using dynamic tags in our CI/CD pipeline.
