name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set image tag
        id: vars
        # shellcheck disable=SC2086
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-')
          if [ "$BRANCH" = "main" ]; then
            TAG="${{ vars.MAJOR }}.${{ vars.MINOR }}"
          else
            TAG="$BRANCH"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rac_font_init:${{ steps.vars.outputs.tag }}
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag image for GitHub Container Registry
        run: |
          docker tag rac_font_init:${{ steps.vars.outputs.tag }} ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}

      - name: Calculate next MINOR version
        if: github.ref == 'refs/heads/main'
        id: calc_minor
        # shellcheck disable=SC2086
        run: echo "NEXT_MINOR=$(( ${{ vars.MINOR }} + 1 ))" >> $GITHUB_OUTPUT
      - uses: mmoyaferrer/set-github-variable@dc880eda800cf0f5332f5b4a5730e86327b96815 # v1.0.0
        if: github.ref == 'refs/heads/main'
        with:
          name: "MINOR"
          value: ${{ steps.calc_minor.outputs.NEXT_MINOR }}
          repository: michael-grosshaeuser/rac_font_init
          token: ${{ secrets.RAC_FONT_INIT }}
