name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rac_font_init:${{ vars.MAJOR }}.${{ vars.MINOR }}
      - name: tag Docker image
        run: docker image tag rac_font_init:${{ vars.MAJOR }}.${{ vars.MINOR }} rac_font_init:latest
      - uses: mmoyaferrer/set-github-variable@v1.0.0
        with:
            name: 'MINOR'
            value: $((${{ vars.MINOR }}+1))
            repository: mmoyaferrer/set-github-variable
            token: ${{ secrets.variable_access_token }}
