name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"
  pull_request:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rac_font_init:${{ vars.MAJOR }}.${{ vars.MINOR }}
      - name: tag Docker image
        run: docker image tag rac_font_init:${{ vars.MAJOR }}.${{ vars.MINOR }} rac_font_init:latest

      - name: Calculate next MINOR version
        id: calc_minor
        run: echo "NEXT_MINOR=$(( ${{ vars.MINOR }} + 1 ))" >> $GITHUB_OUTPUT
      - uses: mmoyaferrer/set-github-variable@dc880eda800cf0f5332f5b4a5730e86327b96815 # v1.0.0
        with:
            name: 'MINOR'
            value: ${{ steps.calc_minor.outputs.NEXT_MINOR }}
            repository: michael-grosshaeuser/rac_font_init
            token: ${{ secrets.RAC_FONT_INIT }}
