name: Renovate check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # jeden Montag um 03:00 Uhr

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Run Renovate
        uses: renovatebot/github-action@0984fb80fc633b17e57f3e8b6c007fe0dc3e0d62 # v40.3.6
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RAC_FONT_INIT }}